using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using OfficeOpenXml;
using SbslFileTransformer.Data;
using SbslFileTransformer.Infrastructure.Helpers;
using SbslFileTransformer.Infrastructure.Messaging;
using SbslFileTransformer.Models;
using SbslFileTransformer.Models.Enums;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace SbslFileTransformer.Infrastructure.Jobs.Reporting.Helpers
{
    public class ReportSender
    {
        private readonly ILogger<ReportEngineJob> logger;
        private readonly IServiceScopeFactory serviceScopeFactory;
        private readonly ReportConfigModel reportConfiguration;

        public ReportSender(ILogger<ReportEngineJob> logger, IServiceScopeFactory serviceScopeFactory, ReportConfigModel reportConfig)
        {
            this.logger = logger;
            this.serviceScopeFactory = serviceScopeFactory;
            this.reportConfiguration = reportConfig;           
        }

        public async Task SendAndSaveReports(List<(ReportModel, Dictionary<int, string>)> newlyProcessedReports, IProgress<int> sendReportProgress)
        {
            using(var scope = this.serviceScopeFactory.CreateScope())
            {
                ApplicationDbContext dbContext = scope.ServiceProvider.GetService<ApplicationDbContext>();
                EmailSender emailSender = scope.ServiceProvider.GetService<EmailSender>();

                var alreadySent = dbContext.ProcessedReports.Select(r => r.ReportId).ToList();

                int count = 0;

                var reportsToSend = new List<ProcessedReport>();

                foreach (var results in newlyProcessedReports)
                {
                    ReportModel report = results.Item1;

                    if (alreadySent.Contains(report.ReportId))
                    {
                        continue;
                    }

                    if (results.Item2.Count > 0)
                    {
                        foreach (KeyValuePair<int, string> key in results.Item2)
                        {
                            
                            //key is the overdue days used to select the email groups
                            var emails = GetEmails(key.Key, report, serviceScopeFactory);

                            //ONLY SEND EMAILS IF FILE HAS 1 OR MORE RECORDS
                            await emailSender.SendMessage(emails,
                                reportConfiguration.EmailHeader + $" Report ID: {report.ReportId}",
                                reportConfiguration.EmailBody + Environment.NewLine + $"{key.Key} Days overdue" +
                                Environment.NewLine +
                                $"Report Name {report.Name}" + Environment.NewLine +
                                //$"Report for {country} for {sprint}" + Environment.NewLine +
                                $"Report generated by: {report.Creator}" + Environment.NewLine +
                                $"COMMENTS:- {report.Notes}", false,
                                new[] { report.TempReportPath, key.Value });

                            await Task.Delay(2500);
                        }
                    }
                    else
                    {
                        if(results.Item1.DaysRange.Length == 0)
                        {
                            results.Item1.DaysRange = new int[]{ 3 };
                        }

                        foreach (var r in results.Item1.DaysRange)
                        {
                            var outputFile = results.Item1.TempReportPath;

                            //change signage for Tz B.P. report
                            if (report.Name.ToLower().Contains("tanzania") && report.Name.ToLower().Contains("clearing")
                                                                           && report.Name.ToLower()
                                                                               .Contains("suspense") &&
                                                                           report.Name.ToLower().Contains("proofing"))
                            {
                                outputFile = await AdjustBalanceValue(results.Item1.TempReportPath);
                            }

                            var emails = GetEmails(r, report, serviceScopeFactory);

                            await emailSender.SendMessage(emails,
                                reportConfiguration.EmailHeader,
                                reportConfiguration.EmailBody + Environment.NewLine +
                                $"Report Name {report.Name}" + Environment.NewLine +
                                //$"Report for {country} for {sprint}" + Environment.NewLine +
                                $"Report generated by: {report.Creator}" + Environment.NewLine +
                                $"COMMENTS:- {report.Notes}",
                                filePaths: new[] { outputFile });
                        }

                        await Task.Delay(2500);
                    }

                    reportsToSend.Add(new ProcessedReport
                    {
                        Format = reportConfiguration.ExportType,
                        ReportId = report.ReportId,
                        Name = report.Name,
                        ProcessedDate = DateTime.Now,
                        Creator = report.Creator,
                        EndTime = report.EndTime,
                        StartTime = report.StartTime,
                        Message = report.Message,
                        Notes = report.Notes,
                        Status = report.Status,
                        UserToken = report.UserToken
                    });

                    count++;

                    sendReportProgress.Report(count * 100 / newlyProcessedReports.Count);
                }

                await SaveToDb(reportsToSend);
            }
        }

        private async Task SaveToDb(List<ProcessedReport> reports)
        {
            using (var scope = serviceScopeFactory.CreateScope())
            {
                ApplicationDbContext dbContext = scope.ServiceProvider.GetService<ApplicationDbContext>();

                dbContext.ProcessedReports.AddRange(reports);

                await dbContext.SaveChangesAsync();
            }
        }

        public static IEnumerable<string> GetEmails(int duration, ReportModel report, IServiceScopeFactory serviceScopeFactory)
        {
            var emails = new List<string>();

            using (var scope = serviceScopeFactory.CreateScope())
            {
                var dbContext = scope.ServiceProvider.GetService<ApplicationDbContext>();

                var groups = dbContext.EmailGroups.Where(g =>
                    g.AgeAlertDuration == duration && g.Country == report.Country && g.Sprint == report.Sprint &&
                    g.Category == report.Category && g.IsActive);

                if (report.Category == ReportCategory.Default)
                    groups = dbContext.EmailGroups.Where(g =>
                        g.AgeAlertDuration == duration && g.Country == report.Country && g.Sprint == report.Sprint && g.IsActive);

                var groupEmails = groups.ToList().Select(g => g.Emails);

                foreach (var group in groupEmails)
                    emails.AddRange(@group.Split(new[] { ',', '\r', '\n' }, StringSplitOptions.RemoveEmptyEntries));

                return emails;
            }
        }

        private async Task<string> AdjustBalanceValue(string inputFile)
        {
            var inputFileName = Path.GetFileName(inputFile);

            var outputFilePath =
                Path.Combine(await FileHelpers.GetTempPath(serviceScopeFactory), "Adj_" + inputFileName);

            using (var package = new ExcelPackage(new FileInfo(inputFile)))
            {
                var sheet = package.Workbook.Worksheets.First();

                var start = sheet.Dimension.Start;
                var end = sheet.Dimension.End;

                for (var i = start.Row + 5; i <= end.Row; i++)
                    if (double.TryParse(sheet.Cells[$"E{i}"].Value.ToString(), out var result))
                        sheet.Cells[$"E{i}"].Value = (1 * result).ToString("N2");//change the (1 * result) to (-1 * result) if need be

                await package.SaveAsAsync(new FileInfo(outputFilePath));
            }

            return outputFilePath;
        }
    }
}
