<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <UserSecretsId>aspnet-SbslFileTransformer-92C8AB10-D7B6-4168-928B-5FC7E66E002C</UserSecretsId>
    <Company>Strategic Business Solutions Ltd</Company>
    <Authors>Bryson Yida</Authors>
    <Product>Sbsl File Transformer</Product>
    <Description>SBSL File Extraction Transformation and Loading Services Tool</Description>
    <Copyright>SBSL</Copyright>
    <PackageProjectUrl>https://www.sbsl.co.ke</PackageProjectUrl>
    <PackageIcon>sbsl.jpg</PackageIcon>
    <RepositoryUrl></RepositoryUrl>
    <ApplicationIcon>sbsl.ico</ApplicationIcon>
  </PropertyGroup>

  <PropertyGroup>
    <PublishWithAspNetCoreTargetManifest>false</PublishWithAspNetCoreTargetManifest>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="LicenseVerify.cer" />
    <None Remove="sbsletl.db-shm" />
    <None Remove="sbsletl.db-wal" />
    <None Remove="sbsletl_logs.db" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="LicenseVerify.cer" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CsvHelper" Version="18.0.0" />
    <PackageReference Include="EPPlus" Version="5.5.2" />
    <PackageReference Include="ExcelDataReader" Version="3.6.0" />
    <PackageReference Include="itext7" Version="7.1.13" />
    <PackageReference Include="MailKit" Version="2.10.0" />
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="3.1.7" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="3.1.7" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="3.1.7" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="3.1.10" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="5.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="3.1.10">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="3.1.10" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="3.1.4" />
    <PackageReference Include="MimeKit" Version="2.10.1" />
    <PackageReference Include="Newtonsoft.Json" Version="12.0.3" />
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="3.2.4" />
    <PackageReference Include="Portable.BouncyCastle" Version="1.8.8" />
    <PackageReference Include="Serilog.AspNetCore" Version="3.4.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="3.1.1" />
    <PackageReference Include="Serilog.Sinks.RollingFile" Version="3.3.0" />
    <PackageReference Include="Serilog.Sinks.SQLite" Version="5.0.0" />
    <PackageReference Include="SSH.NET" Version="2020.0.0" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Images\sbsl.jpg">
      <Pack>True</Pack>
      <PackagePath></PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Licensing\Licensing.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Data\Migrations\" />
    <Folder Include="Migrations\" />
    <Folder Include="Resources\" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Microsoft.Office.Interop.Excel">
      <HintPath>..\..\..\Program Files\Microsoft Office\root\vfs\ProgramFilesX86\Microsoft Office\Office16\DCF\Microsoft.Office.Interop.Excel.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <None Update="DLLs\BouncyCastle.Crypto.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="sbsletl.db">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
