<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <UserSecretsId>aspnet-SbslFileTransformer-92C8AB10-D7B6-4168-928B-5FC7E66E002C</UserSecretsId>
    <Description>SBSL File Extraction Transformation and Loading Services Tool</Description>
    <PackageProjectUrl>https://www.sbsl.co.ke</PackageProjectUrl>
    <PackageIcon>sbsl.jpg</PackageIcon>
    <RepositoryUrl></RepositoryUrl>
    <ApplicationIcon>sbsl.ico</ApplicationIcon>
  </PropertyGroup>

  <PropertyGroup>
    <DefineConstants>STD</DefineConstants>
    <PlatformTarget>x64</PlatformTarget>
    <AssemblyName>SbslFileTransformer</AssemblyName>
    <RootNamespace>SbslFileTransformer</RootNamespace>
    <!--<VersionSuffix>1.0.0.$([System.DateTime]::UtcNow.ToString(mmff))</VersionSuffix>
    <AssemblyVersion Condition=" '$(VersionSuffix)' == '' ">0.0.0.1</AssemblyVersion>
    <AssemblyVersion Condition=" '$(VersionSuffix)' != '' ">$(VersionSuffix)</AssemblyVersion>
    <Version Condition=" '$(VersionSuffix)' == '' ">0.0.1.0</Version>
    <Version Condition=" '$(VersionSuffix)' != '' ">$(VersionSuffix)</Version>-->
    <Company>Strategic Business Solutions Ltd</Company>
    <Authors>Bryson Yida</Authors>
    <Copyright>Copyright © SBSL</Copyright>
    <Product>Sbsl File Transformer</Product>
    <Deterministic>false</Deterministic>
  </PropertyGroup>

  <PropertyGroup>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <GenerateBindingRedirectsOutputType>true</GenerateBindingRedirectsOutputType>
  </PropertyGroup>

  <PropertyGroup>
    <PublishWithAspNetCoreTargetManifest>false</PublishWithAspNetCoreTargetManifest>
    <PackageId>SbslFileTransformer</PackageId>
    <AssemblyVersion>1.0.0.2354</AssemblyVersion>
    <FileVersion>1.0.0.2354</FileVersion>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <Optimize>False</Optimize>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="LicenseVerify.cer" />
    <None Remove="sbsletl.db-shm" />
    <None Remove="sbsletl.db-wal" />
    <None Remove="sbsletl_logs.db" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\GlobalSuppressions.cs" Link="GlobalSuppressions.cs" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="LicenseVerify.cer" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AspNetCore.HealthChecks.UI.Client" Version="3.1.2" />
    <PackageReference Include="CsvHelper" Version="18.0.0" />
    <PackageReference Include="EPPlus" Version="6.2.15" />
    <PackageReference Include="ExcelDataReader" Version="3.6.0" />
    <PackageReference Include="ExcelDataReader.DataSet" Version="3.6.0" />
    <PackageReference Include="Google.Protobuf" Version="3.25.1" />
    <PackageReference Include="HtmlAgilityPack" Version="1.11.55" />
    <PackageReference Include="Humanizer.Core" Version="2.14.1" />
    <PackageReference Include="itext7" Version="7.2.5" />
    <PackageReference Include="MailKit" Version="2.10.0" />
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="3.1.7" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="3.1.7" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="3.1.7" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="3.1.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="3.1.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="3.1.11">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="3.1.10" />
    <PackageReference Include="Microsoft.Extensions.Logging.EventLog" Version="3.1.14" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="3.1.5" />
    <PackageReference Include="MimeKit" Version="2.10.1" />
    <PackageReference Include="MiniProfiler.AspNetCore.Mvc" Version="4.2.22" />
    <PackageReference Include="MiniProfiler.EntityFrameworkCore" Version="4.2.22" />
    <PackageReference Include="MySqlBackup.NET" Version="2.3.3.1" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="3.2.4" />
    <PackageReference Include="Portable.BouncyCastle" Version="1.8.9" />
    <PackageReference Include="Serilog.AspNetCore" Version="3.4.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="3.1.1" />
    <PackageReference Include="Serilog.Sinks.File" Version="5.0.0" />
    <PackageReference Include="Serilog.Sinks.SQLite" Version="5.0.0" />
    <PackageReference Include="SSH.NET" Version="2023.0.0" />
    <PackageReference Include="System.Net.Http" Version="4.3.4" />
    <PackageReference Include="System.Security.Cryptography.Xml" Version="8.0.0" />
    <PackageReference Include="System.Text.Encoding.CodePages" Version="8.0.0" />
    <PackageReference Include="System.Text.Encodings.Web" Version="4.7.2" />
    <PackageReference Include="System.Text.RegularExpressions" Version="4.3.1" />
    <PackageReference Include="X.PagedList.Mvc.Core" Version="8.0.7" />
  </ItemGroup>

  <ItemGroup>
    <None Include="C:\Projects\SBSL\SbslFileTransformer\SbslFileTransformer\.editorconfig" />
    <None Include="Images\sbsl.jpg">
      <Pack>True</Pack>
      <PackagePath></PackagePath>
    </None>
    <None Include="wwwroot\img\loading1.gif" />
    <None Include="wwwroot\img\loading2.gif" />
    <None Include="wwwroot\img\loading3.gif" />
    <None Include="wwwroot\img\loading4.gif" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Licensing\Licensing.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Content\images\" />
    <Folder Include="Data\Migrations\" />
    <Folder Include="logs\" />
    <Folder Include="Resources\" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Microsoft.DotNet.PlatformAbstractions">
      <HintPath>DLLs\Microsoft.DotNet.PlatformAbstractions.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <None Update="AccountsUploads\sample_accounts_format.xlsx">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Content\eula.docx">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Content\eula.rtf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="DLLs\BouncyCastle.Crypto.dll">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
    <None Update="EscalationUploads\sample_escalations.xlsx">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="InstallScripts\Install.ps1">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="InstallScripts\Uninstall.ps1">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="sbsletl.db">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <Target Name="ChangeAliasesOfStrongNameAssemblies" BeforeTargets="FindReferenceAssembliesForReferences;ResolveReferences">
    <ItemGroup>
      <ReferencePath Condition="'%(FileName)' == 'Mysql.Data'">
        <Aliases>MySqlDataAlias</Aliases>
      </ReferencePath>
    </ItemGroup>
  </Target>

  <ItemGroup>
    <EditorConfigFiles Remove="C:\Projects\SBSL\SbslFileTransformer\SbslFileTransformer\.editorconfig" />
  </ItemGroup>

</Project>
